# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Fabric API
fabric_api_version=0.156.0+26.2

# Mod Properties
mod_version = 1.6.0
maven_group = cc.mafien0
archives_base_name = ActionWheel
modid = actionwheel

# Dependencies
modmenu_version=12.0.0-beta.1
ljc_version=1.2.4.2
malilib_version = 1.21.3-0.22.8
